#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus-per-node=1
#SBATCH --job-name=plaba
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=1:00:00
#SBATCH --output=plaba_%A.out  

# activate the environment
source medplaba/bin/activate

MODEL="roberta"

# Run the script
python src/part1/evaluate_plaba.py --model_path /home/tpapandroeu/reproducibility/output/medreadme/roberta_base_binary.pt --data_path /home/tpapandroeu/reproducibility/data/PLABA_2024-Task_1/labeled_sentences.json